name: unity-setup

runs:
  using: composite
  steps:
    # checkout
    - name: Checkout branch
      uses: actions/checkout@v6

    # cache
    - name: Cache Library
      id: cache
      uses: actions/cache@v6
      with:
        path: VRGame/Library
        key: Library-${{ hashFiles('VRGame/Packages/manifest.json') }}
        restore-keys: |
          Library-
