using System.Runtime.CompilerServices;
// [assembly: InternalsVisibleTo("Name_Here")]
[assembly: InternalsVisibleTo("ScriptTemplatesEditTests")]
[assembly: InternalsVisibleTo("ScriptTemplatesPlayTests")]
[assembly: InternalsVisibleTo("RoomEditMode")]
[assembly: InternalsVisibleTo("RoomPlayMode")]
[assembly: InternalsVisibleTo("BrainTests")]
[assembly: InternalsVisibleTo("ServicePlayMode")]
[assembly: InternalsVisibleTo("PlayerServicePlayMode")]
[assembly: InternalsVisibleTo("PlayerServiceEditMode")]
[assembly: InternalsVisibleTo("ScriptTemplatesEditTests")]
[assembly:InternalsVisibleTo("ObjectMatchGameEditModeTest")]